name: Backup to GitHub

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes for testing

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create backup
        run: |
          zip -r backup-$(date +%Y-%m-%d-%H-%M).zip ./

      - name: Upload backup
        uses: actions/upload-artifact@v2
        with:
          name: repository-backup
          path: backup-$(date +%Y-%m-%d-%H-%M).zip
